# Generated by Django 4.2.20 on 2025-08-19 17:39
#
# Reescrita (2026-06-04) para ser agnóstica del motor de base de datos:
# la versión original usaba SQL crudo de SQLite (AUTOINCREMENT, INSERT OR
# IGNORE) y fallaba al migrar sobre PostgreSQL. El comportamiento es el
# mismo; las bases de datos donde ya se aplicó no se ven afectadas.

from django.db import migrations

INSTRUMENTOS = [
    ('Guitarra', 'Cuerdas'),
    ('Piano', 'Teclas'),
    ('Batería', 'Percusión'),
    ('Bajo', 'Cuerdas'),
    ('Violín', 'Cuerdas'),
    ('Saxofón', 'Viento'),
    ('Trompeta', 'Viento'),
    ('Flauta', 'Viento'),
    ('Violonchelo', 'Cuerdas'),
    ('Teclado', 'Teclas'),
]

GENEROS = [
    ('Rock', 'Música rock'),
    ('Jazz', 'Música jazz'),
    ('Pop', 'Música pop'),
    ('Clásica', 'Música clásica'),
    ('Folk', 'Música folk'),
    ('Blues', 'Música blues'),
    ('Reggae', 'Música reggae'),
    ('Electronic', 'Música electrónica'),
    ('Country', 'Música country'),
    ('R&B', 'Rhythm and Blues'),
]

NIVELES_EXPERIENCIA = [
    # (nombre, descripcion, orden, años_minimos, años_maximos)
    ('Principiante', 'De 0 a 2 años de experiencia', 1, 0, 2),
    ('Intermedio', 'De 3 a 5 años de experiencia', 2, 3, 5),
    ('Avanzado', 'De 6 a 10 años de experiencia', 3, 6, 10),
    ('Profesional', 'Más de 10 años de experiencia', 4, 10, None),
]

UBICACIONES = [
    # (nombre, region, orden) — pais='Chile', activo=True para todas
    # Región de Arica y Parinacota
    ('Arica', 'Arica y Parinacota', 1),
    ('Putre', 'Arica y Parinacota', 2),
    # Región de Tarapacá
    ('Iquique', 'Tarapacá', 3),
    ('Alto Hospicio', 'Tarapacá', 4),
    ('Pozo Almonte', 'Tarapacá', 5),
    # Región de Antofagasta
    ('Antofagasta', 'Antofagasta', 6),
    ('Calama', 'Antofagasta', 7),
    ('Tocopilla', 'Antofagasta', 8),
    ('Mejillones', 'Antofagasta', 9),
    # Región de Atacama
    ('Copiapó', 'Atacama', 10),
    ('Vallenar', 'Atacama', 11),
    ('Chañaral', 'Atacama', 12),
    # Región de Coquimbo
    ('La Serena', 'Coquimbo', 13),
    ('Coquimbo', 'Coquimbo', 14),
    ('Ovalle', 'Coquimbo', 15),
    ('Illapel', 'Coquimbo', 16),
    ('Vicuña', 'Coquimbo', 17),
    # Región de Valparaíso
    ('Valparaíso', 'Valparaíso', 18),
    ('Viña del Mar', 'Valparaíso', 19),
    ('Quilpué', 'Valparaíso', 20),
    ('Villa Alemana', 'Valparaíso', 21),
    ('San Antonio', 'Valparaíso', 22),
    ('Quillota', 'Valparaíso', 23),
    ('Los Andes', 'Valparaíso', 24),
    ('San Felipe', 'Valparaíso', 25),
    ('Casablanca', 'Valparaíso', 26),
    # Región Metropolitana
    ('Santiago', 'Metropolitana', 27),
    ('Las Condes', 'Metropolitana', 28),
    ('Providencia', 'Metropolitana', 29),
    ('Ñuñoa', 'Metropolitana', 30),
    ('La Reina', 'Metropolitana', 31),
    ('Vitacura', 'Metropolitana', 32),
    ('Lo Barnechea', 'Metropolitana', 33),
    ('Maipú', 'Metropolitana', 34),
    ('Puente Alto', 'Metropolitana', 35),
    ('La Florida', 'Metropolitana', 36),
    ('Peñalolén', 'Metropolitana', 37),
    ('San Bernardo', 'Metropolitana', 38),
    ('Melipilla', 'Metropolitana', 39),
    ('Talagante', 'Metropolitana', 40),
    # Región del Libertador Bernardo O'Higgins
    ('Rancagua', "O'Higgins", 41),
    ('San Fernando', "O'Higgins", 42),
    ('Rengo', "O'Higgins", 43),
    ('Machalí', "O'Higgins", 44),
    ('Santa Cruz', "O'Higgins", 45),
    # Región del Maule
    ('Talca', 'Maule', 46),
    ('Curicó', 'Maule', 47),
    ('Linares', 'Maule', 48),
    ('Cauquenes', 'Maule', 49),
    ('Constitución', 'Maule', 50),
    # Región de Ñuble
    ('Chillán', 'Ñuble', 51),
    ('San Carlos', 'Ñuble', 52),
    ('Bulnes', 'Ñuble', 53),
    # Región del Biobío
    ('Concepción', 'Biobío', 54),
    ('Talcahuano', 'Biobío', 55),
    ('Chiguayante', 'Biobío', 56),
    ('San Pedro de la Paz', 'Biobío', 57),
    ('Hualpén', 'Biobío', 58),
    ('Los Ángeles', 'Biobío', 59),
    ('Coronel', 'Biobío', 60),
    ('Lota', 'Biobío', 61),
    # Región de La Araucanía
    ('Temuco', 'La Araucanía', 62),
    ('Padre Las Casas', 'La Araucanía', 63),
    ('Villarrica', 'La Araucanía', 64),
    ('Pucón', 'La Araucanía', 65),
    ('Angol', 'La Araucanía', 66),
    # Región de Los Ríos
    ('Valdivia', 'Los Ríos', 67),
    ('La Unión', 'Los Ríos', 68),
    ('Río Bueno', 'Los Ríos', 69),
    # Región de Los Lagos
    ('Puerto Montt', 'Los Lagos', 70),
    ('Osorno', 'Los Lagos', 71),
    ('Castro', 'Los Lagos', 72),
    ('Ancud', 'Los Lagos', 73),
    ('Puerto Varas', 'Los Lagos', 74),
    # Región de Aysén
    ('Coyhaique', 'Aysén', 75),
    ('Puerto Aysén', 'Aysén', 76),
    ('Chile Chico', 'Aysén', 77),
    # Región de Magallanes
    ('Punta Arenas', 'Magallanes', 78),
    ('Puerto Natales', 'Magallanes', 79),
    ('Porvenir', 'Magallanes', 80),
]


def crear_tablas_catalogos(apps, schema_editor):
    """Crear las tablas de Instrumento y Genero si no existen.

    Estos modelos nacieron con managed=False (migración 0011) y pasaron a
    managed=True en 0017 — cambio que no emite DDL. En una base de datos
    nueva, esta migración es la única que crea sus tablas.
    """
    tablas_existentes = schema_editor.connection.introspection.table_names()
    for nombre_modelo in ('Instrumento', 'Genero'):
        modelo = apps.get_model('usuarios', nombre_modelo)
        if modelo._meta.db_table not in tablas_existentes:
            schema_editor.create_model(modelo)


def poblar_datos_iniciales(apps, schema_editor):
    """Insertar datos iniciales de catálogos.

    bulk_create(ignore_conflicts=True) es el equivalente portable del
    INSERT OR IGNORE original: los cuatro catálogos tienen `nombre` único.
    """
    Instrumento = apps.get_model('usuarios', 'Instrumento')
    Genero = apps.get_model('usuarios', 'Genero')
    NivelExperiencia = apps.get_model('usuarios', 'NivelExperiencia')
    Ubicacion = apps.get_model('usuarios', 'Ubicacion')

    Instrumento.objects.bulk_create(
        [Instrumento(nombre=nombre, categoria=categoria)
         for nombre, categoria in INSTRUMENTOS],
        ignore_conflicts=True,
    )
    Genero.objects.bulk_create(
        [Genero(nombre=nombre, descripcion=descripcion)
         for nombre, descripcion in GENEROS],
        ignore_conflicts=True,
    )
    NivelExperiencia.objects.bulk_create(
        [NivelExperiencia(nombre=nombre, descripcion=descripcion, orden=orden,
                          años_minimos=minimos, años_maximos=maximos)
         for nombre, descripcion, orden, minimos, maximos in NIVELES_EXPERIENCIA],
        ignore_conflicts=True,
    )
    Ubicacion.objects.bulk_create(
        [Ubicacion(nombre=nombre, region=region, pais='Chile', activo=True, orden=orden)
         for nombre, region, orden in UBICACIONES],
        ignore_conflicts=True,
    )


def reversar_cambios(apps, schema_editor):
    """Reversar los cambios si es necesario"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_auto_20250819_1338'),
    ]

    operations = [
        migrations.RunPython(crear_tablas_catalogos, reversar_cambios),
        migrations.RunPython(poblar_datos_iniciales, reversar_cambios),
    ]
