# Generated by Django 4.2.20 on 2026-06-05 03:23

from django.db import migrations, models
import django.db.models.functions.text
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', usuarios.models.UsuarioManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='usuario_email_ci_unico'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='usuario_username_ci_unico'),
        ),
    ]
