# Generated by Django 4.2.20 on 2026-06-05 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoMusico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente_nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('remitente_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('remitente_telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo_necesidad', models.CharField(blank=True, choices=[('evento', 'Evento puntual (matrimonio, fiesta, empresa)'), ('recurrente', 'Música en vivo recurrente (bar, restaurante, hotel)'), ('colaboracion', 'Colaboración musical'), ('clases', 'Clases de música'), ('otro', 'Otro')], max_length=60, verbose_name='Tipo de necesidad')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('visto', 'Visto'), ('respondido', 'Respondido'), ('convertido', 'Convertido en trabajo')], default='enviado', max_length=20, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('visto_en', models.DateTimeField(blank=True, null=True)),
                ('ip_remitente', models.GenericIPAddressField(blank=True, null=True)),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='usuarios.perfilmusico', verbose_name='Músico contactado')),
                ('remitente_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario remitente')),
            ],
            options={
                'verbose_name': 'Contacto a músico',
                'verbose_name_plural': 'Contactos a músicos',
                'ordering': ['-creado'],
            },
        ),
    ]
