# Generated by Django 4.2.20 on 2026-06-05 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_contactomusico'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneracionBioIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generaciones_bio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generación de bio con IA',
                'verbose_name_plural': 'Generaciones de bio con IA',
                'ordering': ['-creado'],
            },
        ),
    ]
