# Generated by Django 5.2.15 on 2026-06-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_generacionbioia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRecuperacionPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email solicitado')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de recuperación de contraseña',
                'verbose_name_plural': 'Solicitudes de recuperación de contraseña',
                'ordering': ['-creado'],
            },
        ),
    ]
