# Generated by Django 5.2.15 on 2026-06-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_solicitudrecuperacionpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='terminos_aceptados_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Términos aceptados en'),
        ),
    ]
